### ISSUE TITLE
Reset terms crash

### ISSUE THREAD

**Issue by mtolava** [AlphaNodes/redmine_privacy_terms#5]
Hi
I doing the plugin test but it doesn't work. Right now with the tag 1.0.1 on Redmine 4.0.3-stable on ruby 2.6.6 and rails 5.2
I don't know if this is right, because the logs show me an error when ejecute reset terms button

```
Started GET "/terms/reset" for 127.0.0.1 at 2023-03-01 14:45:46 -0300
Processing by TermsController#reset as HTML
Completed 500 Internal Server Error in 34ms (ActiveRecord: 10.8ms)
  
NoMethodError (private method `settings' called for RedminePrivacyTerms:Module
Did you mean?  setting
               setting?):
  
plugins/redmine_privacy_terms/app/controllers/terms_controller.rb:18:in `reset'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by alexandermeindl** [comment]
Hi @mtolava,
this problem should be solved with the latest version.
